x-log-config: &log-config
  logging:
    driver: json-file
    options:
      max-size: "50m"
      max-file: "5"
volumes:
  lws:
  lwsdata:
  lwsadmin:
  lwstor:
services:
  tor:
    container_name: lwstor
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-tor
    restart: unless-stopped
    volumes:
      - lwstor:/var/lib/tor/
    network_mode: host
    <<: *log-config
  lws:
    container_name: lws
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile-lws
    restart: unless-stopped
    network_mode: host
    volumes:
      - lws:/root/.bitmonero/light_wallet_server
      - lwsdata:/data
    environment:
      SCAN_THREADS: 24
      REST_THREADS: 8
      REST_SERVER: http://127.0.0.1:8080
      ADMIN_REST_SERVER: http://127.0.0.1:8081
      LOG_LEVEL: 1
      DAEMON_ZMQ_PUB: tcp://127.0.0.1:18082
      DAEMON_ZMQ_SUB: tcp://127.0.0.1:18083
      CORS: "*"
      MAX_SUBADDRESS: 20000
    <<: *log-config
  lwsadmin:
    container_name: lwsadmin
    build:
      context: lwsadmin
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - tor
      - lws
    environment:
      LWS_URL: http://127.0.0.1:8080
      LWS_ADMIN_URL: http://127.0.0.1:8081
      QUART_ENV: production
      HOST: 0.0.0.0
      DEBUG: 0
      SERVER_NAME: ${SERVER_NAME:-127.0.0.1:5000}
      SECRET_KEY: ${SECRET_KEY:-thisisasecret}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      LWS_EXTERNAL_URL: ${LWS_EXTERNAL_URL:-http://127.0.0.1:8080}
    volumes:
      - lwsadmin:/srv/lwsadmin/data
      - lwstor:/var/lib/tor:ro
      - lwsdata:/data:ro
    network_mode: host
    <<: *log-config
