"""payments

Revision ID: c07b27f5146a
Revises: dc82ecfb7151
Create Date: 2026-01-05 20:20:10.290642

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c07b27f5146a'
down_revision = 'dc82ecfb7151'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment',
    sa.Column('tx_hash', sa.String(length=150), nullable=False),
    sa.Column('create_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('account_id', sa.String(length=80), nullable=True),
    sa.Column('amount', sa.BigInteger(), nullable=True),
    sa.Column('price_per_block', sa.BigInteger(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('dropped', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('tx_hash'),
    sa.UniqueConstraint('tx_hash')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payment')
    # ### end Alembic commands ###