"""accounts

Revision ID: dc82ecfb7151
Revises: d95f75cd9514
Create Date: 2026-01-05 15:41:56.415050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc82ecfb7151'
down_revision = 'd95f75cd9514'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.String(length=80), nullable=False),
    sa.Column('create_date', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('address', sa.String(length=150), nullable=True),
    sa.Column('view_key', sa.String(length=150), nullable=True),
    sa.Column('payment_account_id', sa.Integer(), nullable=True),
    sa.Column('payment_address_id', sa.Integer(), nullable=True),
    sa.Column('payment_address', sa.String(length=150), nullable=True),
    sa.Column('start_height', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('payment_address'),
    sa.UniqueConstraint('payment_address_id'),
    sa.UniqueConstraint('view_key')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account')
    # ### end Alembic commands ###