"""accounts can be active or not

Revision ID: e2bc465ed3aa
Revises: c07b27f5146a
Create Date: 2026-01-06 00:31:20.207611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2bc465ed3aa'
down_revision = 'c07b27f5146a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['tx_hash'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')

    with op.batch_alter_table('account', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###