FROM ubuntu@sha256:c35e29c9450151419d9448b0fd75374fec4fff364a27f176fb458d472dfc9e54

RUN apt-get update && apt-get install tor -y

RUN mkdir -p /run/tor /var/lib/tor/lws \
  && chown -R debian-tor:debian-tor /run/tor /var/lib/tor/lws \
  && chmod 700 -R /run/tor /var/lib/tor/lws

COPY dockerfiles/torrc /etc/tor/torrc

USER debian-tor

EXPOSE 9050

ENTRYPOINT ["tor"]